royxk/codeit_team4_project

src/apiFetcher/customAxios.js
src/apiFetcher/recipients/deleteRecipient.js
src/apiFetcher/recipients/getAllRecipients.js
src/apiFetcher/recipients/postRecipient.js

· Recipipents API 연동
· CustomAxios 설정

feat#8 : Recipients API 연동

---

index.html
src/components/core/RelationBadge.jsx
src/components/modal/Modal.jsx
src/components/modal/ModalPortal.jsx
src/hooks/useOutSideClick.js

모달 컴포넌트 작성완료
Home.jsx에서 해당 방식으로 테스트 가능합니다

feat: modal component

---

src/components/core/RecipientListBlock.jsx

입력 값(data : object)에 따라 사용자 이미지와 카운트를 보여주는 컴포넌트 작성.
data = {
count : number,
profileImageURL : string[]
}
· 프로필 이미지는 최대 3개까지 노출
· 카운트는 3명을 초과한 시점부터 노출

feat#21 : RecipientListBlock 컴포넌트 작성

---

src/apiFetcher/backgroundImages.js
src/components/Input/Input.jsx
src/components/core/ImageButton.jsx
src/pages/PaperCreate.jsx

아래 컬러 or 이미지 선택가능
데이터 추가 버튼 누르고 조회하면 나옴 (추후에 지울꼐여)

feat#38 Completed

---

src/Router.jsx
src/apiFetcher/customAxios.js
src/apiFetcher/recipients/getRecipientMessages.js
src/components/core/RelationBadge.jsx
src/components/core/RollingPaper.jsx
src/components/modal/Modal.jsx
src/components/modal/ModalTest.jsx
src/pages/Papers.jsx

현재까지 작업한 부분 올립니다
추가 작업 필요한 부분
- 무한스크롤
- toast컴포넌트 이벤트
- (선택) 모달 애니메이션

Feat#25 : paper page

---

src/components/header/NavOptionalBar.jsx
src/components/header/emoji/TopEmojiBlock.jsx

· Card 컴포넌트에서도 사용할 수 있도록 분리
· emojiData와 maxLength를 props로 받음

fix#47 : TopEmoji 컴포넌트화

---

src/apiFetcher/customAxios.js
src/components/core/EmptyPaper.jsx
src/components/core/Toast.jsx
src/components/modal/Modal.jsx
src/pages/Papers.jsx

무한스크롤 제외 작업 완료입니다
merge되고 추가 작업 들어가겠습니다

Feat#48: paperList 페이지에 무한스크롤을 제외한 모든 기능

---

src/assets/images/arrowLeftButton.svg
src/assets/images/arrowRightButton.svg
src/components/core/Button/ArrowLeftButton.jsx
src/components/core/Button/ArrowRightButton.jsx

refector#84 arrowButton만들기

---

package-lock.json
package.json
src/common/quill.js
src/common/whitelist.js

· DOMPurify 패키지 설치
· changeInnerHTMLSafely 작성
· whitelist 작성

feat#83 : XSS 방지를 위한 HTML Filter 로직 구현

---

src/common/quill.js
src/utils/changeInnerHTMLSafely.js

#refactor#90 : changeInnerHTMLSafely 위치 변경

---

src/components/core/FetchMore.jsx

- 무한스크롤 클린업함수로 인한 페이지 이동시 발생하는 에러 수정했습니다

hotFix: 무한스크롤 함수로 인한 페이지 이동 에러 수정

---

src/pages/Papers.jsx

<Button variant={"primary"} size={40} text="삭제하기" />
=>
<Button variant={"primary"} size={40}>삭제하기
이런식으로 수정!
PaperCreate 부분 button은 import를 주석처리 해두셨길래 안건드렸습니다!

fix#100 Button내용 수정

---

src/components/header/emoji/TopEmojiBlock.jsx

fix#102 : TopEmojiBlock 수정

---

src/components/core/FetchMore.jsx
src/components/core/RollingPaper.jsx
src/components/modal/Modal.jsx
src/pages/Papers.jsx
src/styles/GlobalStyle.js

텍스트 에디터에서 넘겨주는 텍스트 효과 적용되어서 보여지도록 수정

feat: htmlSafely apply

---

src/components/core/RollingPaper.jsx
src/components/modal/Modal.jsx

feat: font apply

---

src/apiFetcher/messages/deleteMessage.js
src/apiFetcher/recipients/deleteRecipient.js
src/components/core/RollingPaper.jsx
src/pages/Papers.jsx

- 롤링페이퍼 삭제기능
- 메시지 삭제기능
- 롤링페이지 삭제버튼 버그 수정
- 메시지 이미지 가득차게 수정

feat: 이미지 가득차게 변경 및 롤링페이퍼&메시지 삭제기능

---

src/components/core/Button/ToggleButton.jsx

hover와 active는 정해진게 없어서 제 취향을 담아서 만들었습니다.

Feat#87 ToggleButton 제작

---

src/common/validation/validateName.js
src/components/Input/Input.jsx
src/pages/MessageCreate.jsx

<Input 컴포넌트 element>
· id : form에서 인식할 id
· placeholder : 빈 입력칸에 나타날 글자
· onChange : 입력이 변경될 때 발생할 함수
· error : 에러를 판별할 함수
· errorMessage : 에러 함수가 true일 때 나올 메시지
· ref : input 외부 클릭 시 오류가 나타날 수 있도록 부여할 useRef
· maxLength : input에서 수용 가능한 최대 글자 길이

feat#137 : Input 컴포넌트 수정 작업 및 에러 메시지 추가

---

src/components/modal/Modal.jsx

fix: modal profile image

---

src/components/core/CardList/Card.jsx

- 이모지 상단 가로선 추가
- 이미지 카드 글자색 반전 및 배경 밝기 조절
- 제목 width값 조절 및 일정 글자수 초과 시 '...' 으로 대체

refector#139 card수정

---

src/components/core/DropDown.jsx
src/pages/MessageCreate.jsx

- 드롭다운 컴포넌트로 교체한뒤 그에 해당하는 로직 수정

feat: 드롭다운 변경에 따른 로직 수정
